Lecture/do
kyohoonsim/kusf-data-2023-2-dev pull request #14
Opened 2023-09-21 20:18 UTC by dolzi

ㅜㅠ 밤샛네요,,

이걸로도 수업 비슷하거나 아슬하거나 그럴거같은데,
혹시모르니 내일 점심시간까지 정렬이랑 집계함수까지 올려볼게요

2023-09-22 05:33 UTC, kyohoonsim requested changes
밤새 강의자료 만드시느라 고생 많으셨습니다.ㅜㅜ 몇개 부분 수정 요청 드립니다!

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/04_데이터베이스의 활용-데이터베이스란.md
> +  - 논리적인 작업의 단위를 묶어서 DML에 의해 조작된 결과를 작업단위(트랜잭션) 별로 제어할 때 사용
트랜잭션이라는 개념이 많이 낯설 것 같은데, 뭔가 이해할 수 있는 예시가 있으면 좋을 것 같습니다.

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +  - LIKE : 특정 문자나 문자열이 포함되어 있는지 검색하고 싶은 경우
양쪽에 %가 있는 예시도 있으면 좋을 것 같습니다.

수업을 놓친 학생은 잘 모를 수도 있을 것 같아서요. ㅎㅎ

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +```
INSERT 할 때 모든 컬럼에 대한 데이터를 삽입할 때는 VALUE 앞 (필드1, 필드2, ...) 이 없어도 된다는 예시가 있으면 좋을 것 같습니다.

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +```
모든 데이터 행을 삭제하는 것과 관련된 예시가 있으면 좋을 것 같습니다.

`DELETE FROM player;`

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +> 3-1. 조원들 정보를 INSERT
어떤 테이블에 insert를 해야하는지. 새로 만들어야 하는지 조금 더 구체적인 정보를 알려줘야 할 것 같아요.

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +    - 영어 : z-a
숫자에 대한 것도 추가되면 좋을 것 같습니다.

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +```sql
CREATE에 대한 자세한 설명은 이후 강의에서 진행될 것이라는 코멘트가 강의자료에 있으면 좋을 것 같습니다.

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +> 5-2. student 테이블의 나이 합계, 평균 나이, 가장 많은 나이, 가장 적은 나이 출력
결과 화면을 캡쳐한 걸 넣어주시고, 이걸 구현해달라고 하는 게 좋을 것 같습니다. 

캡쳐 화면 또는 추가 설명 필요.

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +
HAVING을 적용하기 전 예제가 하나 더 있으면 좋을 것 같습니다.

2023-09-22 05:33 UTC, kyohoonsim commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +
결과 화면 추가(전체적으로 쿼리 실행 결과 화면이 있으면 좋을 것 같습니다)

2023-09-22 05:43 UTC, dolzi commented on lectures/04_데이터베이스의 활용-데이터베이스란.md
> +  - 논리적인 작업의 단위를 묶어서 DML에 의해 조작된 결과를 작업단위(트랜잭션) 별로 제어할 때 사용
개념 추가했습니다. 강의 설명할때 예시도 함께 설명하겠습니다

2023-09-22 05:57 UTC, dolzi commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +  - LIKE : 특정 문자나 문자열이 포함되어 있는지 검색하고 싶은 경우
음.. 해당 케이스 수정하려고 전체 문서를 다시 봤는데.. 위와 같은 경우의 수가 너무 많씀니다 .. ! 저거 넣으면< > != 에 대한 케이스도 넣어야할고,, IN도 NOT IN도 넣어야할 거같고.. NULL도 IS NOT NULL등... GROUP BY HAVING WHERE 등등등.. 

수업시간 관련해서 나오는 구문에 대해서 활용할 수 있게 잘 설명해보는 방법은 어떨까요 ?

2023-09-22 06:00 UTC, dolzi commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +```
추가했습니다

2023-09-22 06:03 UTC, dolzi commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +```
추가했습니다

2023-09-22 06:03 UTC, dolzi commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +> 3-1. 조원들 정보를 INSERT
추가했습니다

2023-09-22 06:03 UTC, dolzi commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +    - 영어 : z-a
추가했습니다

2023-09-22 06:06 UTC, dolzi commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +```sql
여기말고 CREATE 처음 시작하는 부분에 문구 하나 추가했습니다..

2023-09-22 06:06 UTC, dolzi commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +> 5-2. student 테이블의 나이 합계, 평균 나이, 가장 많은 나이, 가장 적은 나이 출력
이건 문제가 많아서 퇴근하고 일괄적으로 적용하겠습니다

2023-09-22 06:07 UTC, dolzi commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +
이것도 위에 말씀 드린 내용처럼 모든 경우의 수 예제를 넣는 건 쉽지 않을 것 같습니다 ㅜ 

활용할 수 있도록 자세히 잘 설명하는 건 어떨까요 ?

2023-09-22 06:08 UTC, dolzi commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +
요것도 일괄 적용하겠슴다 !

2023-09-22 06:11 UTC, dolzi commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +
일단.. 추가했습니다 !

추가하니까 WHERE절에 대한 내용도 넣어야하나 싶고 ㅠ

2023-09-22 06:18 UTC, kyohoonsim approved these changes

2023-09-22 06:18 UTC, kyohoonsim commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
> +
일단 제가 말씀드린 것 정도만 추가하시죠 ㅋㅋ

2023-09-22 06:19 UTC, kyohoonsim commented on lectures/05_데이터베이스의 활용-SQL 기초1.md
> +  - LIKE : 특정 문자나 문자열이 포함되어 있는지 검색하고 싶은 경우
일단 제가 말씀 드린 정도만 추가하시죠 ㅋㅋ 나머지는 설명으로!

2023-09-22 06:32 UTC, kyohoonsim approved these changes

2023-09-22 13:29 UTC, kyohoonsim requested changes
예시 이미지들 하나씩 만드시느라 고생하셨습니다. 

한 군데 정도 표현이 어색한 부분이 있어서 코멘트 남겨뒀습니다.

2023-09-22 13:29 UTC, kyohoonsim commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
>  > 4-1. student 테이블에서 나이로 내림차순으로 출력 (단, 같은 데이터가 있을 시, 이름을 내림차순으로 한다.)
나이로 내림차순으로 출력 -> 나이를 기준으로 내림차순으로 정렬하여 출력한다.

이름을 내림차순으로 한다 -> 이름을 기준으로 내림차순으로 정렬한다.

이렇게 수정해보는 건 어떨까요?

2023-09-23 00:44 UTC, kyohoonsim approved these changes

2023-09-23 00:44 UTC, dolzi commented on lectures/06_데이터베이스의 활용-SQL 기초2.md
>  > 4-1. student 테이블에서 나이로 내림차순으로 출력 (단, 같은 데이터가 있을 시, 이름을 내림차순으로 한다.)
fixed !

2023-09-23 00:44 UTC, merged