change file names
kyohoonsim/kusf-data-2023-2-dev pull request #15
Opened 2023-09-23 00:53 UTC by dolzi

file name 변경했습니다

2023-10-03 11:48 UTC, kyohoonsim approved these changes

2023-10-05 13:13 UTC, kyohoonsim requested changes

2023-10-05 13:13 UTC, kyohoonsim commented on lectures/08_데이터베이스의 활용-SQL 심화.md
> +
이 쯤에 CASE WHEN THEN 문법이 들어가는 건 어떨까요?

2023-10-05 22:46 UTC, dolzi commented on lectures/08_데이터베이스의 활용-SQL 심화.md
> +
추가했습니다 ~ 혹시 더 추가되어져야할 함수있으시면 말씀주세요 !

2023-10-05 23:00 UTC, kyohoonsim requested changes

2023-10-05 23:00 UTC, kyohoonsim commented on lectures/08_데이터베이스의 활용-SQL 심화.md
> +
DATE_FORMAT, MONTH, YEAR 등 날짜 관련 함수들 몇 개 추가해주시면 좋을 것 같습니다.

2023-10-05 23:16 UTC, dolzi commented
DATE_FORMAT으로 웬만한 부분은 다 해결이 될 것 같구, 강의 하면서 참고 url을 통해서 YEAR MONTH DAY도 같이 설명 하도록 하겠습니다 !

2023-10-05 23:42 UTC, kyohoonsim approved these changes
고생하셨습니다 ㅎㅎ

2023-10-05 23:43 UTC, kyohoonsim commented
> DATE_FORMAT으로 웬만한 부분은 다 해결이 될 것 같구, 강의 하면서 참고 url을 통해서 YEAR MONTH DAY도 같이 설명 하도록 하겠습니다 !

조옿습니다

2023-10-07 00:45 UTC, kyohoonsim approved these changes
수고하셨습니다 ㅎㅎ

2023-10-07 00:45 UTC, merged